version: '3'
services:
  master:
    build: .
    ports:
      - "8108:8108"
    entrypoint: "./bin/pdb-cluster localhost 8108 Y"
    links:
      - worker_1
      - worker_2
  worker_1:
    build: .
    ports:
      - "8109:8109"
    entrypoint: "./bin/pdb-server 1 512 master:8108 localhost:8109"
  worker_2:
     build: .
     ports:
       - "8110:8110"
     entrypoint: "./bin/pdb-server 1 512 master:8108 localhost:8110"

